if(F){.rs.restartR()}

######################### R Libraries Required #################################
################################################################################
library(lessR)
library(shinyWidgets)
library(shiny)
library(shinydashboard)
library(dashboardthemes)
library(openxlsx)
library(readxl)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
library(lubridate)
library(sjlabelled)
library(tidyverse)
library(zoo)
library(DT)
library(plotly)
library(shinycssloaders)
library(rtf)
library(xtable)
library(kableExtra)
library(shinyalert)
library(viridis)
############################### MAIN APP #######################################

plotTitlesize = 11
plotAxissize = 9


indata = 'fitbit.xlsx'


ui <- dashboardPage(
  # dashboard title
  title = "Fitbit Fitness Dashboard",
  dashboardHeader(
    title = shinyDashboardLogo(
      theme = "blue_gradient",
      boldText = "Fitbit",
      mainText = " Viz Dashboard",
      badgeText = "1.0"
    )),
  
  dashboardSidebar(
    sidebarUserPanel(name = textOutput("text1"),
                     subtitle = a(href = "#",
                                  icon("circle",
                                       class = "text-success"),
                                  "Online")
    ),
    sidebarMenu(
      id = "tabs",
      # upload data & demographic information
      menuItem(text = "Fitbit Data", tabName = "user_profile", 
               icon = icon("table")),
      # data exploratory analysis & activity review
      menuItem(text = "Individual Activity Dashboard", tabName = "dashboard", 
               icon = icon("chart-line")),
      menuItem(text = "Multiple Activity Dashboard", tabName = "mdashboard", 
               icon = icon("chart-bar"))#,
    ),
    width = "250px",
    collapsed = FALSE
  ),
  
  dashboardBody(
    useShinyalert(),
    # upload theme
    shinyDashboardThemes(
      theme = "blue_gradient"),
    tabItems(
      tabItem(
        # User profile & demographic input        
        tabName = "user_profile",
        h3("Fitbit Data", tagList(shiny::icon("table"))),
        p('The purpose of this dashboard is to help explore ',tags$a(href="https://www.kaggle.com/arashnic/fitbit", "FitBit Fitness Tracker Data"),'. These datasets were generated by respondents 
          to a distributed survey via Amazon Mechanical Turk between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented 
          to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring.'),
        p('For computational purpose, the data used is limited to 3 patients and 4 weeks of data from 04.12.2016-05.12.2016. 
          If you have any questions, feel free to reach out to at',tags$a(href="https://www.linkedin.com/in/andydang14/", tagList(shiny::icon("linkedin")))),
        fluidRow(
          box(selectInput("sample_data",
                          "Choose a sample sheet",
                          choices = c("Hourly Steps",
                                      "Hourly Calories",
                                      "Hourly Intensities",
                                      #"Hourly Stand",
                                      "Daily Steps",
                                      "Daily Intensities",
                                      "Daily Activity",
                                      "Sleep Minutes",
                                      "Daily Sleep"#,
                                      #"Daily Stand"
                                      ))#,
              # Download 'template' / sample data set
              #downloadButton("download_sample",
              #               "Download Sample Data"),
              # Use sample data set
              #actionButton(
              #  inputId = "use_sample",
              #  label = "Use Sample Data",
              #  class = "btn-primary")
          ),
          uiOutput('show_variable'),
          # preview sample data set sheet selected
          #box(tableOutput("sample_table"), width = 12)
          box(
            #DTOutput("sample_table") %>% withSpinner(color='#000000',type = 3, color.background='white'), 
            #tableOutput("sample_table") %>% withSpinner(color='#000000',type = 3, color.background='white'),
            div(style = 'overflow-x: scroll', tableOutput("sample_table") %>% withSpinner(color='#000000',type = 3, color.background='white')), 
            width = 12)
        )
      ),
      tabItem(
        # Activity Dashboard & Exploratory Analysis
        tabName = "dashboard",
        h3("Individual Activity Dashboard", tagList(shiny::icon("chart-line"))),
        dateRangeInput(
          inputId='dateRange',
          label='Select Start/End Dates',
          start = '2016-04-12',
          end = '2016-05-12',
          min = '2016-04-12',
          max = '2016-05-12',
          format = "yyyy-mm-dd"
        ),
        selectInput(
          inputId = 'patId',
          label = 'Patient ID',
          choices = c(4020332650,6962181067,5553957443),
          selected = c(4020332650)
        ),
        actionButton(
          inputId = 'show_graphs',
          label = 'Generate Graphs',
          class = "btn-primary"
        ),
        p(),
        br(),
        fluidRow(
          # tab for steps analysis
          tabBox(
            title = tagList(shiny::icon("walking"), "Steps"),
            id = "steps", height = "auto",
            tabPanel(
              title = "Hourly", 
              #plotOutput(outputId = "hourlysteps")),
              plotlyOutput(outputId = "hourlysteps") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "Weekly", 
              #plotOutput(outputId = "dailysteps")),
              plotlyOutput(outputId = "dailysteps") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "All Time", 
              #plotOutput(outputId = "historicsteps")),
              plotlyOutput(outputId = "historicsteps") %>% withSpinner(color='#000000',type = 3, color.background='white'))
          ),
          # tab for calories burnt analysis
          tabBox(
            title = tagList(shiny::icon("running"), "Calories"),
            id = "cals", height = "auto",
            tabPanel(
              title = "Hourly", 
              #plotOutput(outputId = "hourlycalories")),
              plotlyOutput(outputId = "hourlycalories") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "Weekly", 
              #plotOutput(outputId = "weeklycalories")),
              plotlyOutput(outputId = "weeklycalories") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "All Time", 
              #plotOutput(outputId = "historiccalories"))
              plotlyOutput(outputId = "historiccalories") %>% withSpinner(color='#000000',type = 3, color.background='white'))
          ),
          # tab for intensity analysis
          tabBox(
            title = tagList(shiny::icon("dumbbell"), "Intensity"),
            id = "intensity", height = "auto",
            tabPanel(
              title = "Daily", 
              #plotOutput(outputId = "dailyintensity")),
              plotlyOutput(outputId = "dailyintensity") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "Weekly", 
              #plotOutput(outputId = "weeklyintensity")),
              plotlyOutput(outputId = "weeklyintensity") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "All Time", 
              #plotOutput(outputId = "historicintensity"))
              plotlyOutput(outputId = "historicintensity") %>% withSpinner(color='#000000',type = 3, color.background='white'))
          ),
          # tab for distance analysis
          tabBox(
            title = tagList(shiny::icon("road"), "Distance"),
            id = "distance", height = "auto",
            tabPanel(
             title = "Daily",
             #plotOutput(outputId = "dailydist")),
             plotlyOutput(outputId = "dailydist") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "Weekly", 
              #plotOutput(outputId = "weeklydist")),
              plotlyOutput(outputId = "weeklydist") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "All Time", 
              #plotOutput(outputId = "historicdist"))
              plotlyOutput(outputId = "historicdist") %>% withSpinner(color='#000000',type = 3, color.background='white'))
          ),        
          # tab for sleep analysis
          tabBox(
            title = tagList(shiny::icon("bed"), "Sleep"),
            id = "sleep", height = "auto", width = 12,
            # tabPanel(
            #   title = "Daily", 
            #   #plotOutput(outputId = "dailysleep")),
            #   plotlyOutput(outputId = "dailysleep") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "Weekly", 
              #plotOutput(outputId = "weeklysleep")),
              plotlyOutput(outputId = "weeklysleep") %>% withSpinner(color='#000000',type = 3, color.background='white')),
            tabPanel(
              title = "All Time", 
              #plotOutput(outputId = "historicsleep"))
              plotlyOutput(outputId = "historicsleep") %>% withSpinner(color='#000000',type = 3, color.background='white'))
          )
        )
      ),
      tabItem(
        # Activity Dashboard & Exploratory Analysis
        tabName = "mdashboard",
        h3("Multiple Activity Dashboard", tagList(shiny::icon("chart-bar"))),
        selectInput(
          inputId = 'patIdm',
          label = 'Patient ID',
          choices = c(4020332650,6962181067,5553957443),
          selected = c(4020332650),
          multiple=T
        ),
        actionButton(
          inputId = 'show_graphs_m',
          label = 'Generate Graphs',
          class = "btn-primary"
        ),
        p(),
        tabBox(
          title = tagList(shiny::icon("walking"), "Metrics"),
          id = "sleep", height = "auto", width = 12,
          tabPanel(
            title = "StepCount",
            #plotOutput(outputId = "dailysleep")),
            plotlyOutput(outputId = "stepM") %>% withSpinner(color='#000000',type = 3, color.background='white')),
          tabPanel(
            title = "Calories", 
            #plotOutput(outputId = "weeklysleep")),
            plotlyOutput(outputId = "calM") %>% withSpinner(color='#000000',type = 3, color.background='white')),
          tabPanel(
            title = "Itensity",
            #plotOutput(outputId = "dailysleep")),
            plotlyOutput(outputId = "intenM") %>% withSpinner(color='#000000',type = 3, color.background='white')),
          tabPanel(
            title = "Sleep", 
            #plotOutput(outputId = "historicsleep"))
            plotlyOutput(outputId = "sleepM") %>% withSpinner(color='#000000',type = 3, color.background='white'))
        )
      ),
      tabItem(
        # Activity Dashboard & Exploratory Analysis
        tabName = "report",
        h3("Generate Report", tagList(shiny::icon("download"))),
        box(
          pickerInput('plot_list','Plots to include:',
                      choices=c(
                        'Hourly Steps','Weekly Steps','All Time Steps',
                        'Hourly Calories','Weekly Calories','All Time Calories',
                        'Daily Intensity','Weekly Intensity','All Time Intensity',
                        'Daily Distance','Weekly Distance','All Time Distance',
                        'Weekly Sleep','All Time Sleep',
                        'Comparison Step','Comparison Calories','Comparison Intensity','Comparison Sleep'
                      ),
                      selected=NULL,multiple=TRUE,options=list(`actions-box`=TRUE)),
          selectInput(
            inputId = 'report_type',
            label = 'Report Type',
            choices = c('HTML'
                        #,'DOC'
                        ),
            selected = 'HTML'
          ),
          # Download 'template' / sample data set
          actionButton("download_report",
                       "Download Report")
          # downloadButton("download_report",
          #                "Download Report")
        )
        
      )
      # DELETE?
      # tabItem(
      #   tabName = "subitem1",
      #   h3("Don't Break The Chain", tagList(shiny::icon("calendar-check"))),
      #   fluidRow(
      #     box(
      #       h4("Historical Goal Completion"),
      #       plotOutput(outputId = "BreakChain")
      #     ),
      #     box(
      #       h4("Streak Count"),
      #       plotOutput(outputId = "activity_streak")
      #     )
      #   ),
      #   h3("Daily Tracker", tagList(shiny::icon("watch-fitness"))),
      #   fluidRow(
      #     box(
      #       h4("Daily Steps Goal"),
      #       plotOutput(outputId = "step_goal_plot")
      #     ),
      #     box(
      #       h4("Daily Stand Goal"),
      #       plotOutput(outputId = "stand_goal_plot")
      #     ),
      #     box(
      #       h4("Daily Excercise Goal"),
      #       plotOutput(outputId = "calories_goal_plot")
      #     )
      #   )
      # ),
      # tabItem(
      #   tabName = "subitem2",
      #   h3("Historical Weight", tagList(shiny::icon("dumbbell"))),
      #   fluidRow(
      #     box(
      #       plotOutput(outputId = "weightLogInfo_plot") , width = 12
      #     )
      #   ),
      #   h3("Weight Loss Tracker", tagList(shiny::icon("bullseye"))),
      #   fluidRow(
      #     box(
      #       valueBoxOutput("calories", width = 12) ,width = 12
      #     ),
      #     box(
      #       valueBoxOutput("Target", width = 6),
      #       valueBoxOutput("Prediction", width = 6),width = 12
      #     )
      #   )
      # )
    ) # tab items
  ) # end body
) # end dash page


server <- function(input, output, session) {
  
  ############################# USER PROFILE #####################################
  sample_Input <- reactive({
    req(input$sample_data)
    # select data set to show in preview
    print(getwd())
    switch(input$sample_data,
           "Hourly Steps" = as_tibble(read_excel(indata,
                                                     sheet="hourlySteps",
                                                     col_name=T)),
           "Hourly Calories" = as_tibble(read_excel(indata,
                                                        sheet="hourlyCalories",
                                                        col_name=T)),
           "Hourly Intensities" = as_tibble(read_excel(indata,
                                                           sheet="hourlyIntensities",
                                                           col_name=T)),
           # "Hourly Stand" = as_tibble(read_excel(indata,
           #                                           sheet="hourlyStand",
           #                                           col_name=T)),
           "Daily Steps" = as_tibble(read_excel(indata,
                                                    sheet="dailySteps",
                                                    col_name=T)),
           "Daily Intensities" = as_tibble(read_excel(indata,
                                                          sheet="dailyIntensities",
                                                          col_name=T)),
           "Daily Activity" = as_tibble(read_excel(indata,
                                                       sheet="dailyActivity",
                                                       col_name=T)),
           "Sleep Minutes" = as_tibble(read_excel(indata,
                                                      sheet="minuteSleep",
                                                      col_name=T)),
           "Daily Sleep" = as_tibble(read_excel(indata,
                                                    sheet="sleepDay",
                                                    col_name=T))#,
           #"Daily Stand" = as_tibble(read_excel(indata,
          #                                          sheet="standDay",
          #                                          col_name=T))
    )
  })
  
  
  sample_table = reactive({
    #req(input$show_vars,input$sample_data,sample_Input())
    #sample_Input()[,input$show_vars] %>% mutate(Id=as.factor(Id))
    sample_Input() %>% slice(1:15)
  })
  
  
  output$sample_table <- function(){
    #req(input$show_vars,input$sample_data)
    sample_table() %>%
    kable("html") %>% kable_styling(c("striped","hover"), full_width = TRUE)
  }
  
  
  if(F){
  observeEvent(input$sample_data,{
    updatePickerInput(session,'show_vars',choices=names(sample_Input()),selected=names(sample_Input()))
  })
  
  output$show_variable <- renderUI({
    box(
      pickerInput('show_vars','Select Variables',choices=NULL,selected=NULL,multiple=TRUE,options=list(`actions-box`=TRUE))
    )
  })
  }
  
  ########################## ACTIVITY DASHVBOARD #################################
  
  # Hourly Steps
  hourlySteps <- reactive({
    req(input$show_graphs)
    #input$use_sample
    #c(input$use_uploaded, input$use_sample)
    # prepare the hourly steps data from either uploaded or sample data    
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  hsteps <- read_excel(input$user_data$datapath, sheet = "hourlySteps")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
    hsteps <- read_excel(indata, sheet = "hourlySteps")
    #}
    hsteps <- as.data.frame(hsteps)
    print(str(hsteps))
    hsteps$ActivityHour <- as.POSIXct(hsteps$ActivityHour, format="%Y-%m-%d")
    hsteps
  })
  
  # hourly steps graph
  h_step_grph <- reactive({
    req(input$show_graphs)
    hourlySteps() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; hsteps %>% filter(Id==patId) %>%
      group_by(Hour) %>%
      summarize(StepTotal = mean(StepTotal)) %>%
      ggplot(aes(x=Hour, y= StepTotal, fill = StepTotal))+
      geom_col()+
      scale_fill_continuous(low = '#05fbd7', high = "#17667b") +
      labs(title = "Hourly Steps") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) 
  })
  
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
  #observe(
    output$hourlysteps <- renderPlotly(
      ggplotly(p=h_step_grph(),tooltip=c('x','y')) %>% config(displayModeBar = F)
    )
  )
  
  # Weekly Steps
  weeklySteps <- reactive({
    
    c(input$show_graphs)
    
    #c(input$use_uploaded, input$use_sample)
    # prepare the daily steps data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  dsteps <- read_excel(input$user_data$datapath, sheet = "dailySteps")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      dsteps <- read_excel(indata, sheet = "dailySteps")
    #}
    dsteps <- as.data.frame(dsteps)
    print(str(dsteps))
    dsteps$ActivityDay <- as.POSIXct(dsteps$ActivityDay, format = "%Y-%m-%d")
    dsteps <- subset(dsteps)
    dsteps
  })
  
  
  w_step_grph <- reactive({
    c(input$show_graphs)
    weeklySteps() %>% 
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
    # # patId=4020332650; dsteps %>% filter(Id==patId) %>%
      group_by(WkDay) %>%
      summarise(StepTotal=mean(StepTotal,na.rm=T)) %>%
    ggplot(aes(x = WkDay, y = StepTotal)) +
      geom_bar(stat = "identity", fill = "#3aafa9") +
      labs(title = "Weekly Steps",
           x = "Date", y = "Weekly Steps") +
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))
  })
  
  # daily steps graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$dailysteps <- renderPlotly(
      ggplotly(p=w_step_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # Historic Steps
  historicSteps <- reactive({
    c(input$show_graphs)
    # c(input$use_uploaded, input$use_sample)
    # prepare the historic steps data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  histsteps <- read_excel(input$user_data$datapath, sheet = "dailySteps")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      histsteps <- read_excel(indata, sheet = "dailySteps")
    #}
    histsteps <- as.data.frame(histsteps)
    print(str(histsteps))
    histsteps
  })
  
  hi_step_grph <- reactive({
    c(input$show_graphs)
    historicSteps() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; histsteps %>% filter(Id==patId) %>%
      ggplot(aes(x = ActivityDay, y = StepTotal)) +
      geom_line(color = "#2cdeeb", size = 1) + 
      geom_point(color = "#2cdeeb", size = 3) + 
      xlab("Date")+
      ylab("Total Steps")+
      labs(title = "All Time Steps") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))
  })
  
  # historic steps graph
  observeEvent(
    c(input$show_graphs),
    #c(input$use_uploaded, input$use_sample),
    ignoreInit = T,
    output$historicsteps <- renderPlotly(
      ggplotly(p=hi_step_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # Hourly Calories
  hourlyCalories <- reactive({
    c(input$show_graphs)
    # prepare the hourly calories data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  hcal <- read_excel(input$user_data$datapath, sheet = "hourlyCalories")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      hcal <- read_excel(indata, sheet = "hourlyCalories")
    #}
    hcal <- as.data.frame(hcal)
    print(str(hcal))
    hcal$ActivityHour <- as.POSIXct(hcal$ActivityHour, format="%Y-%m-%d")
    hcal
  })
  
  h_cal_grph <- reactive({
    c(input$show_graphs)
    hourlyCalories() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; hcal %>% filter(Id==patId) %>%
      group_by(Hour) %>%
      summarize(CaloriesTotal = mean(Calories)) %>%
      ggplot(aes(x=Hour, y= CaloriesTotal, fill = CaloriesTotal))+
      geom_col()+
      scale_fill_continuous(low = '#05fbd7', high = "#17667b") +
      labs(title = "Hourly Calories") +
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))
  })
  
  
  
  # hourly calories graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$hourlycalories <- renderPlotly(
      ggplotly(p=h_cal_grph()) %>% config(displayModeBar = F)
    )
  )
  
  
  # Weekly Calories
  weeklyCalories <- reactive({
    c(input$show_graphs)
    #c(input$use_uploaded, input$use_sample)
    # prepare the weekly calories data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  wcal <- read_excel(input$user_data$datapath, sheet = "dailyActivity")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      wcal <- read_excel(indata, sheet = "dailyActivity")
    #}
    wcal <- as.data.frame(wcal)
    print(str(wcal))
    wcal$ActivityDate <-as.POSIXct(wcal$ActivityDate, format = "%Y-%m-%d")
    wcal
  })
  
  w_cal_grph <- reactive({
    c(input$show_graphs)
    weeklyCalories() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; wcal %>% filter(Id==patId) %>%
      group_by(WkDay) %>% mutate(Calories=mean(Calories,na.rm=T)) %>% ungroup() %>%
    ggplot(aes(x = WkDay, y = Calories)) + 
      geom_col(fill='#3aafa9') +
      labs(title = "Weekly Calories ",
           x = "Date", y = "Weekly Calories") +
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))
  })
  
  
  
  
  # weekly calories graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$weeklycalories <- renderPlotly(
      ggplotly(p=w_cal_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # Historic Calories
  historicCalories <- reactive({
    c(input$show_graphs)
    # prepare the historic calories data from either uploaded or sample data    
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  histcal <- read_excel(input$user_data$datapath, sheet = "dailyActivity")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      histcal <- read_excel(indata, sheet = "dailyActivity")
    #}
    histcal <- as.data.frame(histcal)
    print(str(histcal))
    histcal
  })
  
  hi_cal_grph <- reactive({
    c(input$show_graphs)
    historicCalories() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; wcal %>% filter(Id==patId) %>%
    ggplot(aes(x = ActivityDate, y = Calories))+
      geom_line(color = "#2cdeeb", size = 1) + 
      geom_point(color = "#2cdeeb", size = 3) + 
      xlab("Date")+
      ylab("Calories Burned")+
      labs(title = "All Time Calories") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))
  })
  
  
  # historical calories graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$historiccalories <- renderPlotly(
      ggplotly(p=hi_cal_grph()) %>% config(displayModeBar = F)
    )
  )
  
  
  ##### INTENSITY #####
  # Daily Intensities
  dailyIntensity <- reactive({
    c(input$show_graphs)
    # prepare the daily intensities data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  dint <- read_excel(input$user_data$datapath, sheet = "hourlyIntensities")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      dint <- read_excel(indata, sheet = "hourlyIntensities")
    #}
    dint <- as.data.frame(dint)
    dint$ActivityHour <- as.POSIXct(dint$ActivityHour, format = "%Y-%m-%d")
    dint
  })
  
  d_int_grph <- reactive({
    c(input$show_graphs)
    dailyIntensity() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; dint %>% filter(Id==patId) %>%
    ggplot(
           aes(x=ActivityHour, y= AverageIntensity, fill = AverageIntensity))+
      geom_col()+
      scale_fill_continuous(low = '#05fbd7', high = "#17667b") +
      labs(title = "Daily Intensities") +
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))      
  })
  
  # daily intensity graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$dailyintensity <- renderPlotly(
      ggplotly(p=d_int_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # Weekly Intensities
  weeklyIntensity <- reactive({
    c(input$show_graphs)
    # prepare the weekly intensities data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  wint <- read_excel(input$user_data$datapath, sheet = "dailyIntensities")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      wint <- read_excel(indata, sheet = "dailyIntensities")
    #}
    wint <- as.data.frame(wint)
    print(str(wint))
    wint$ActivityDay <- as.POSIXct(wint$ActivityDay, format = "%Y-%m-%d")
    wint <- wint %>% select(ActivityDay, 
                            Id,
                            WkDay,
                            VeryActiveMinutes, 
                            FairlyActiveMinutes, 
                            LightlyActiveMinutes) %>%  data.frame()
    wint <- melt(wint, id.vars = c("ActivityDay",'Id','WkDay'))
    wint
  })
  
  w_int_grph <- reactive({
    c(input$show_graphs)
    weeklyIntensity() %>%
      filter(Id==input$patId) %>%
      filter(ActivityDay >= input$dateRange[1] & ActivityDay <= input$dateRange[2]) %>%
    # patId=4020332650; wint %>% filter(Id==patId) %>%
      group_by(WkDay,variable) %>% summarise(value=mean(value,na.rm=T)) %>%
    ggplot(
           aes(fill = variable, y=value, x = WkDay)) +
      geom_bar(position = position_fill(reverse = TRUE), stat="identity") +
      labs(title = "Weekly Intensities") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) +
      scale_colour_manual(values = c('LightlyActiveMinutes' = '#05fbd7',
                                     'FairlyActiveMinutes' = '#17667b',
                                     'VeryActiveMinutes' = "#f8766d"),
                          aesthetics = "fill")
  })
  
  # weekly intensity graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$weeklyintensity <- renderPlotly(
      ggplotly(p=w_int_grph()) %>% config(displayModeBar = F)
    )
  )  
  
  # Historic Intensities
  historicIntensity <- reactive({
    c(input$show_graphs)
    # prepare the historic intensities data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  hint <- read_excel(input$user_data$datapath, sheet = "dailyIntensities")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      hint <- read_excel(indata, sheet = "dailyIntensities")
    #}
    hint <- as.data.frame(hint)
    print(str(hint))
    hint <- hint %>% select(ActivityDay, 
                            Id,
                            VeryActiveMinutes, 
                            FairlyActiveMinutes, 
                            LightlyActiveMinutes) %>%  data.frame()
    hint <- melt(hint, id.vars = c("ActivityDay",'Id'))
    hint
  })
  
  hi_int_grph <- reactive({
    historicIntensity() %>%
      filter(ActivityDay >= input$dateRange[1] & ActivityDay <= input$dateRange[2]) %>%
    # patId=4020332650; hint %>% filter(Id==patId) %>%
    ggplot(
           aes(fill = variable, y=value, x = ActivityDay)) +
      geom_bar(position = position_fill(reverse = TRUE), stat="identity") +
      labs(title = "All Time Intensities") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) +
      scale_colour_manual(values = c('LightlyActiveMinutes' = '#05fbd7',
                                     'FairlyActiveMinutes' = '#17667b',
                                     'VeryActiveMinutes' = "#f8766d"),
                          aesthetics = "fill")
  })
  
  # historic intensity graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$historicintensity <- renderPlotly(
      ggplotly(p=hi_int_grph()) %>% config(displayModeBar = F)
    )
  )    
  
  
  # Daily Distance
  dailyDistance <- reactive({
    c(input$show_graphs)
    
    ddist <- read_excel(indata, sheet = "dailyActivity")
    ddist <- as.data.frame(ddist)
    print(str(ddist))
    ddist$ActivityDate <- as.POSIXct(ddist$ActivityDate, format = "%Y-%m-%d")
    ddist <- ddist %>% select(ActivityDate, 
                              Id,
                              VeryActiveDistance, 
                              ModeratelyActiveDistance, 
                              LightActiveDistance) %>%  data.frame()
    ddist <- melt(ddist, id.vars = c("ActivityDate",'Id'))
    ddist
  })
  
  d_dist_grph <- reactive({
    c(input$show_graphs)
    dailyDistance() %>% 
      filter(Id==input$patId) %>%
      filter(ActivityDate >= input$dateRange[1] & ActivityDate <= input$dateRange[2]) %>%
      # patId=4020332650; ddist %>% filter(Id==patId) %>%
    ggplot(aes(x = ActivityDate, y=value, fill=variable)) +
      geom_col(position = "dodge") +
      labs(title = "Daily Distance") + 
      
      
      #scale_fill_continuous(low = '#8EE4AF', high = "#379683") +
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
             panel.grid.major = element_line(colour = "#f4f4f4"))+
      scale_fill_manual(values = c('LightActiveDistance' = '#05fbd7',
                                     'ModeratelyActiveDistance' = '#17667b',
                                     'VeryActiveDistance' = "#f8766d"))
    
  })
  
  # daily intensity graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$dailydist <- renderPlotly(
      ggplotly(p=d_dist_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # Weekly Distance
  weeklyDistance <- reactive({
    c(input$show_graphs)
    # prepare the weekly distance data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  wdist <- read_excel(input$user_data$datapath, sheet = "dailyActivity")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      wdist <- read_excel(indata, sheet = "dailyActivity")
    #}
    wdist <- as.data.frame(wdist)
    print(str(wdist))
    wdist$ActivityDate <- as.POSIXct(wdist$ActivityDate, format = "%Y-%m-%d")
    wdist <- wdist %>% select(ActivityDate, 
                              Id,
                              WkDay,
                              VeryActiveDistance, 
                              ModeratelyActiveDistance, 
                              LightActiveDistance) %>%  data.frame()
    wdist <- melt(wdist, id.vars = c("ActivityDate","Id","WkDay"))
    wdist
  })
  
  w_dist_grph <- reactive({
    c(input$show_graphs)
    weeklyDistance() %>%
     filter(Id==input$patId) %>%
      filter(ActivityDate >= input$dateRange[1] & ActivityDate <= input$dateRange[2]) %>%
      # patId=4020332650; wdist %>% filter(Id==patId) %>%
      group_by(WkDay,variable) %>% summarise(value=mean(value,na.rm=T)) %>% ungroup() %>%
    ggplot(
           aes(fill = variable, y=value, x = WkDay)) +
      geom_bar(position = position_fill(reverse = TRUE), stat="identity") +
      labs(title = "Weekly Distance") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) + 
      scale_colour_manual(values = c('LightActiveDistance' = '#05fbd7',
                                     'ModeratelyActiveDistance' = '#17667b',
                                     'VeryActiveDistance' = "#f8766d"),
                          aesthetics = "fill")
  })
  
  # weekly distance graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$weeklydist <- renderPlotly(
      ggplotly(p=w_dist_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # Historic Distance
  historicDistance <- reactive({
    c(input$show_graphs)
    # prepare the historic distance data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  hdist <- read_excel(input$user_data$datapath, sheet = "dailyActivity")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      hdist <- read_excel(indata, sheet = "dailyActivity")
    #}
    hdist <- as.data.frame(hdist)
    print(str(hdist))
    hdist <- hdist %>% select(ActivityDate, 
                              Id,
                              VeryActiveDistance, 
                              ModeratelyActiveDistance, 
                              LightActiveDistance) %>%  data.frame()
    hdist <- melt(hdist, id.vars = c("ActivityDate",'Id'))
    hdist
  })
  
  hi_dist_grph <- reactive({
    c(input$show_graphs)
    historicDistance() %>%
      filter(Id==input$patId) %>%
      filter(ActivityDate >= input$dateRange[1] & ActivityDate <= input$dateRange[2]) %>%
      # patId=4020332650; wdist %>% filter(Id==patId) %>%
    ggplot(
           aes(fill = variable, y= value, x = ActivityDate)) +
      geom_bar(position = position_fill(reverse = TRUE), stat="identity") + 
      labs(title = "All Time Distance") +
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) + 
      scale_colour_manual(values = c('LightActiveDistance' = '#05fbd7',
                                     'ModeratelyActiveDistance' = '#17667b',
                                     'VeryActiveDistance' = "#f8766d"),
                          aesthetics = "fill")
  })
  
  # historic distance graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$historicdist <- renderPlotly(
      ggplotly(p=hi_dist_grph()) %>% config(displayModeBar = F)
    )
  )   
  
  # Weekly Sleep
  weeklySleep <- reactive({
    c(input$show_graphs)
    # prepare the weekly sleep data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  wsleep <- read_excel(input$user_data$datapath, sheet = "sleepDay")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      wsleep <- read_excel(indata, sheet = "sleepDay")
    #}
    wsleep$SleepDay <- as.POSIXct(wsleep$SleepDay, format = "%Y-%m-%d")
    wsleep <- as.data.frame(wsleep)
    print(str(wsleep))
    wsleep
  })
  
  w_sle_grph <-  reactive({
    c(input$show_graphs)
    weeklySleep() %>%
      filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; wsleep %>% filter(Id==patId) %>%
      group_by(WkDay) %>% summarise(TotalMinutesAsleep=mean(TotalMinutesAsleep),TotalTimeInBed=mean(TotalTimeInBed)) %>%
      pivot_longer(.,cols=c('TotalMinutesAsleep','TotalTimeInBed'),names_to = 'Type',values_to = 'TotalTime') %>%
    ggplot() +
      geom_col(aes(x = WkDay, y = TotalTime, fill=Type), position = 'dodge') +
      labs(title = "Weekly Sleep", x = "Date", y = "Weekly Sleep") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) + 
      scale_colour_manual(values = c('TotalMinutesAsleep' = '#05fbd7',
                                     #'TotalTimeInBed' = '#17667b',
                                     'TotalTimeInBed' = "#f8766d"),
                          aesthetics = "fill")
      
  })
  
  # weekly sleep graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$weeklysleep <- renderPlotly(
      ggplotly(p=w_sle_grph()) %>% config(displayModeBar = F)
    )
  )  
  
  # Historic Sleep
  historicSleep <- reactive({
    c(input$show_graphs)
    # prepare the historic sleep data from either uploaded or sample data
    #if (is.null(input$user_data) == F & is.null(input$use_uploaded) == F) {
    #  hsleep <- read_excel(input$user_data$datapath, sheet = "sleepDay")
    #}
    #else if (is.null(input$user_data) == T | is.null(input$use_sample) == F) {
      hsleep <- read_excel(indata, sheet = "sleepDay")
    #}
    hsleep$SleepDay <- as.POSIXct(hsleep$SleepDay, format = "%Y-%m-%d")
    hsleep <- as.data.frame(hsleep)
    print(str(hsleep))
    hsleep
  })
  
  hi_sle_grph <- reactive({
    c(input$show_graphs)
    historicSleep() %>%
     filter(Id==input$patId) %>%
      filter(JustDate >= input$dateRange[1] & JustDate <= input$dateRange[2]) %>%
      # patId=4020332650; hsleep %>% filter(Id==patId) %>%
    ggplot() +
      geom_line(aes(x = SleepDay, y = TotalMinutesAsleep),color = "#05fbd7", size = 1) + 
      geom_point(aes(x = SleepDay, y = TotalMinutesAsleep),color = "#05fbd7", size = 3) + 
      geom_line(aes(x = SleepDay, y = TotalTimeInBed),color = "#f8766d", size = 1) + 
      geom_point(aes(x = SleepDay, y = TotalTimeInBed),color = "#f8766d", size = 3) + 
      xlab("Date") +
      ylab("Sleep Time (in Minutes)") +
      labs(title = "All Time Sleep") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4"))
  })
  
  # historic sleep graph
  observeEvent(
    c(input$show_graphs),
    ignoreInit = T,
    output$historicsleep <- renderPlotly(
      ggplotly(p=hi_sle_grph()) %>% config(displayModeBar = F)
    )
  )   
  
  
  ##### MULTIPLE #####
  # step 
  M_step_grph <- reactive({
    c(input$show_graphs_m)
    historicSteps() %>%
      filter(Id%in%input$patIdm) %>%
      mutate(Id = factor(Id)) %>%
      ggplot(aes(x = ActivityDay, y = StepTotal, color = Id)) +
      geom_line(size = 1) + 
      geom_point(size = 3) + 
      xlab("Date")+
      ylab("Total Steps")+
      labs(title = "Steps Comparison") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) +
      #scale_color_viridis(discrete=TRUE, option="inferno") +
      scale_colour_manual(values = c('#05fbd7','#17667b',"#f8766d"))
  })
  
  observeEvent(
    c(input$show_graphs_m),
    #c(input$use_uploaded, input$use_sample),
    ignoreInit = T,
    output$stepM <- renderPlotly(
      ggplotly(p=M_step_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # cal
  M_cal_grph <- reactive({
    c(input$show_graphs_m)
    historicCalories() %>%
      filter(Id%in%input$patIdm) %>%
      # patId=4020332650; wcal %>% filter(Id==patId) %>%
      ggplot(aes(x = ActivityDate, y = Calories, color=factor(Id)))+
      geom_line(size = 1) + 
      geom_point(size = 3) + 
      xlab("Date")+
      ylab("Calories Burned")+
      labs(title = "Calories Comparison") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) +
      #scale_color_viridis(discrete=TRUE, option="inferno") +
      scale_colour_manual(values = c('#05fbd7','#17667b',"#f8766d"))
  })
  
  
  # calories graph
  observeEvent(
    c(input$show_graphs_m),
    ignoreInit = T,
    output$calM <- renderPlotly(
      ggplotly(p=M_cal_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # sleep graph
  M_sle_grph <- reactive({
    c(input$show_graphs_m)
    historicSleep() %>%
      filter(Id%in%input$patIdm) %>%
      ggplot() +
      geom_line(aes(x = SleepDay, y = TotalMinutesAsleep, color=factor(Id)),size = 1) + 
      geom_point(aes(x = SleepDay, y = TotalMinutesAsleep, color=factor(Id)),size = 3) + 
      xlab("Date") +
      ylab("Sleep Time (in Minutes)") +
      labs(title = "Sleep Comparison") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) +
      #scale_color_viridis(discrete=TRUE, option="inferno") +
      scale_colour_manual(values = c('#05fbd7','#17667b',"#f8766d"))
  })
  
  # historic sleep graph
  observeEvent(
    c(input$show_graphs_m),
    ignoreInit = T,
    output$sleepM <- renderPlotly(
      ggplotly(p=M_sle_grph()) %>% config(displayModeBar = F)
    )
  )
  
  # itensity graph
  M_int_grph <- reactive({
    c(input$show_graphs_m)
    historicIntensity() %>%
      filter(Id%in%input$patIdm) %>%
      # patId=4020332650; hint %>% 
      ggplot(aes(color = factor(Id), y=value, x = ActivityDay, group=factor(Id))) +
      geom_line() +
      labs(title = "Intensities Comparison") + 
      theme(plot.title = element_text(size = plotTitlesize, face = "bold", hjust = 0.5),
            axis.text = element_text(size = plotAxissize),
            axis.title = element_text(size = plotAxissize, face = "bold"),
            panel.background = element_rect(fill = "white"),
            axis.line = element_line(size = 1, colour = "black"),
            panel.grid.major = element_line(colour = "#f4f4f4")) +
      #scale_color_viridis(discrete=TRUE, option="inferno") +
      scale_colour_manual(values = c('#05fbd7','#17667b',"#f8766d")) +
      facet_wrap(~factor(Id))
  })
  
  # historic intensity graph
  observeEvent(
    c(input$show_graphs_m),
    ignoreInit = T,
    output$intenM <- renderPlotly(
      ggplotly(p=M_int_grph()) %>% config(displayModeBar = F)
    )
  )
  
  ##### REPORT #####
  if(F){
  output$download_report = downloadHandler(
    filename = "report.html",
    #filename = paste0('report.',tolower(input$report_type)),
    
    content = function(file) {
      #withProgress(message = 'Rendering, please wait!', {
        
        listName = c(
          'Hourly Steps','Weekly Steps','All Time Steps',
          'Hourly Calories','Weekly Calories','All Time Calories',
          'Daily Intensity','Weekly Intensity','All Time Intensity',
          'Daily Distance','Weekly Distance','All Time Distance',
          'Weekly Sleep','All Time Sleep',
          'Comparison Step','Comparison Calories','Comparison Intensity','Comparison Sleep'
        )
        
        Ls = list(
          h_step_grph(),w_step_grph(),hi_step_grph(),
          h_cal_grph(),w_cal_grph(),hi_cal_grph(),
          d_int_grph(),w_int_grph(),hi_int_grph(),
          d_dist_grph(),w_dist_grph(),w_dist_grph(),
          w_sle_grph(),hi_sle_grph(),
          M_step_grph(),M_cal_grph(),M_int_grph(),M_sle_grph()
        )
        
        names(Ls)=listName
        
        notchosen = setdiff(listName,input$plot_list)
        
        for(i in notchosen) Ls[[i]] = NULL
        
        # write_rds(x=Ls,file='allplots.rds')
        
        # if(input$report_type=='DOC'){
        # rtf=RTF("report.doc" ,width=10,height=12,font.size=10)
        # for(i in input$plot_list){
        #   addHeader(rtf,title=i)
        #   addPlot(rtf,plot.fun=print,width=5,height=4,res=100, Ls[[i]])
        # }
        # done(rtf)
        # 
        # file.copy("report.doc", file)
        # } else {
          #tempReport = file.path(tempdir(), "report.Rmd")
          #file.copy("report.Rmd", tempReport, overwrite = TRUE)
          
          report_path = tempfile(fileext = ".Rmd")
          file.copy("report.Rmd", report_path, overwrite = TRUE)
          
          # Set up parameters to pass to Rmd document
          params = list(Ls = Ls)
          
          # Knit the document, passing in the `params` list, and eval it in a
          # child of the global environment (this isolates the code in the document
          # from the code in this app).
          # rmarkdown::render(tempReport, output_file = file,
          #                   params = params,
          #                   envir = new.env(parent = globalenv())
          # )
          
          rmarkdown::render(report_path, 
                            output_file = file,
                            params = params,
                            envir = new.env(parent = globalenv())
          )
          
        #}
        
      #})
    }
  )
  }
  
  observeEvent(input$download_report, {
    # Show a modal when the button is pressed
    shinyalert("Oops!", paste0("This feature is not available right now through shinyapps.io\n 
                               Please contact the author for further assistance!"), type = "error")
  })
  
  observe({
    # Show a modal when the button is pressed
    shinyalert("Welcome To My Fitbit App", type = "success")
  })
  
  
  
}

# Run the application 
shinyApp(ui = ui, server = server)

